<a href="https://colab.research.google.com/github/faajr/telco/blob/main/TELCO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

url = "https://raw.githubusercontent.com/faajr/telco/main/dataset%20telco.xlsx"

df = pd.read_excel(url)

df.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Cluster,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Jogja,Bandng,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010
1,TEL-000002,SUB1687,10/07/2024,SBY,Yogyakarta,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332
2,TEL-000003,SUB3131,13/03/2024,Yogyakarta,Jakrta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577
3,TEL-000004,SUB4293,11/02/2026,Bandng,Jakrta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707
4,TEL-000005,SUB4930,Jan-16-2026,SBY,Jakarta,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593

In [24]:
print(df.shape)
df.info()

(10000, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Txn_ID           10000 non-null  object
 1   Subscriber_ID    9432 non-null   object
 2   Activation_Date  10000 non-null  object
 3   Area             10000 non-null  object
 4   Cluster          10000 non-null  object
 5   Package_Type     10000 non-null  object
 6   Package_Name     10000 non-null  object
 7   Usage_GB         10000 non-null  int64
 8   Package_Price    10000 non-null  float64
 9   Discount_Pct     9190 non-null   float64
 10  Recharge_Amount  10000 non-null  float64
 11  Network_Cost     10000 non-null  float64
 12  Channel          10000 non-null  object
 13  Payment_Method   10000 non-null  object
 14  Tenure_Month     10000 non-null  int64
 15  Churn_Flag       6673 non-null   object
 16  NPS_Score        10000 non-null  int64
 17  Target_ARPU      10000 non-null  int64
dtypes: float64(4), int64(4), object(10)
memory usage: 1.4+ MB

In [25]:
print(df.columns)

Index(['Txn_ID', 'Subscriber_ID', 'Activation_Date', 'Area', 'Cluster',
       'Package_Type', 'Package_Name', 'Usage_GB', 'Package_Price',
       'Discount_Pct', 'Recharge_Amount', 'Network_Cost', 'Channel',
       'Payment_Method', 'Tenure_Month', 'Churn_Flag', 'NPS_Score',
       'Target_ARPU'],
      dtype='object')

In [26]:
df.rename(columns={'Cluster': 'Province'}, inplace=True)

In [27]:
print(df['Area'].value_counts())

Area
SBY           1032
Surabaya      1028
JKT           1025
Jogja         1020
Jakarta       1018
Jakrta        1008
Bandung        979
JAKARTA        978
Yogyakarta     964
Bandng         948
Name: count, dtype: int64

In [28]:
df['Province'] = df['Province'].map({
    'Surabaya': 'Jawa Timur',
    'Sby': 'Jawa Timur',
    'Yogyakarta': 'DIY',
    'Jogja': 'DIY',
    'Jakrta': 'Jakarta',
    'Bandng': 'Jawa Barat',
    'Bandung': 'Jawa Barat'
})

In [29]:
print(df['Area'].value_counts())

Area
SBY           1032
Surabaya      1028
JKT           1025
Jogja         1020
Jakarta       1018
Jakrta        1008
Bandung        979
JAKARTA        978
Yogyakarta     964
Bandng         948
Name: count, dtype: int64

In [30]:
df['Area'] = df['Area'].map({
    'SBY': 'Surabaya',
    'JKT': 'Jakarta',
    'Jogja': 'Yogyakarta',
    'Jakrta': 'Jakarta',
    'Bandng': 'Bandung'
})

In [31]:
print(df['Area'].value_counts())

Area
Jakarta       2033
Surabaya      1032
Yogyakarta    1020
Bandung        948
Name: count, dtype: int64

In [32]:
print(df['Province'].value_counts())

Province
Jawa Timur    2566
DIY           2537
Jawa Barat    2479
Jakarta       1241
Name: count, dtype: int64

In [33]:
df['Province'].isnull().sum()

np.int64(1177)

In [34]:
df.isnull().sum()

Txn_ID                0
Subscriber_ID       568
Activation_Date       0
Area               4967
Province           1177
Package_Type          0
Package_Name          0
Usage_GB              0
Package_Price         0
Discount_Pct        810
Recharge_Amount       0
Network_Cost          0
Channel               0
Payment_Method        0
Tenure_Month          0
Churn_Flag         3327
NPS_Score             0
Target_ARPU           0
dtype: int64

In [35]:
#menambahkan kolom profit
df['Profit'] = df['Recharge_Amount'] - df['Network_Cost']
df.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU,Profit
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,Jawa Barat,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010,805.83
1,TEL-000002,SUB1687,10/07/2024,Surabaya,DIY,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332,-17.38
2,TEL-000003,SUB3131,13/03/2024,NaN,Jakarta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577,-92.57
3,TEL-000004,SUB4293,11/02/2026,Bandung,Jakarta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707,1152.86
4,TEL-000005,SUB4930,Jan-16-2026,Surabaya,NaN,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593,566.24

In [36]:
import numpy as np

In [37]:
df['NPS_Category'] = np.where(df['NPS_Score'] < 51, 'Buruk',
np.where((df['NPS_Score'] >= 51) & (df['NPS_Score'] <= 85), 'Bagus', 'Bagus Sekali'))
df.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,Jawa Barat,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010,805.83,Bagus
1,TEL-000002,SUB1687,10/07/2024,Surabaya,DIY,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332,-17.38,Bagus Sekali
2,TEL-000003,SUB3131,13/03/2024,NaN,Jakarta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577,-92.57,Bagus Sekali
3,TEL-000004,SUB4293,11/02/2026,Bandung,Jakarta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707,1152.86,Bagus
4,TEL-000005,SUB4930,Jan-16-2026,Surabaya,NaN,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593,566.24,Buruk

In [38]:
df['Activation_Date'].max()

'Sep-30-2025'

In [39]:
df.columns

Index(['Txn_ID', 'Subscriber_ID', 'Activation_Date', 'Area', 'Province',
       'Package_Type', 'Package_Name', 'Usage_GB', 'Package_Price',
       'Discount_Pct', 'Recharge_Amount', 'Network_Cost', 'Channel',
       'Payment_Method', 'Tenure_Month', 'Churn_Flag', 'NPS_Score',
       'Target_ARPU', 'Profit', 'NPS_Category'],
      dtype='object')

In [40]:
df['Activation_Date'] = pd.to_datetime(df['Activation_Date'], format='mixed', dayfirst=True)
df.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,Recharge_Amount,Network_Cost,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,Jawa Barat,Data,Package_31,10,306.02,NaN,3060.20,2254.37,Retail,Cash,0,NaN,63,96010,805.83,Bagus
1,TEL-000002,SUB1687,2024-07-10,Surabaya,DIY,Data,Package_12,17,133.81,0.95,113.74,131.12,Dealer,Ewallet,57,NaN,86,76332,-17.38,Bagus Sekali
2,TEL-000003,SUB3131,2024-03-13,NaN,Jakarta,Data,Package_61,14,194.08,0.10,1976.69,2069.26,dealer,Transfer,81,N,96,154577,-92.57,Bagus Sekali
3,TEL-000004,SUB4293,2026-02-11,Bandung,Jakarta,Voice,Package_94,7,794.58,0.15,4727.75,3574.89,Online,Ewallet,108,NaN,54,91707,1152.86,Bagus
4,TEL-000005,SUB4930,2026-01-16,Surabaya,NaN,Data,Package_34,13,81.33,0.05,1588.11,1021.87,Online,Transfer,19,Y,27,182593,566.24,Buruk

In [41]:
df['Activation_Date'].head()

0   2024-12-06
1   2024-07-10
2   2024-03-13
3   2026-02-11
4   2026-01-16
Name: Activation_Date, dtype: datetime64[ns]

In [42]:
df['NPS_Score'].head()

0    63
1    86
2    96
3    54
4    27
Name: NPS_Score, dtype: int64

In [43]:
# ARPU per Area
df.groupby('Area')['Target_ARPU'].mean()

Area
Bandung       109011.880802
Jakarta       109528.942941
Surabaya      108772.096899
Yogyakarta    112817.383333
Name: Target_ARPU, dtype: float64

In [44]:
# NPS per Area
df.groupby('Area')['NPS_Score'].mean()

Area
Bandung       49.636076
Jakarta       49.853419
Surabaya      50.327519
Yogyakarta    49.893137
Name: NPS_Score, dtype: float64

In [45]:
# Berdasarkan nilai NPS_score kategori < 51 buruk Churn_Flag (Y: Churn) selain itu N
df['Churn_Flag'] = np.where(df['NPS_Score'] < 51, 'Y', 'N')

In [46]:
# ARPU_Gap --> selisih pendapatan aktual (Recharge_Amount) vs target (Target_ARPU)
df['ARPU_Gap'] = df['Recharge_Amount'] - df['Target_ARPU']

In [47]:
# kategorikan cat_target_ARPU jika positif = mencapai (Y) dan negatif = tidak mencapai (N)
def cat_target_ARPU (x) :
  if x <= 0 :
    return 'N'
  else :
    return 'Y'
df['cat_target_ARPU'] = df['ARPU_Gap'].apply(cat_target_ARPU)
df.head()

,Txn_ID,Subscriber_ID,Activation_Date,Area,Province,Package_Type,Package_Name,Usage_GB,Package_Price,Discount_Pct,...,Channel,Payment_Method,Tenure_Month,Churn_Flag,NPS_Score,Target_ARPU,Profit,NPS_Category,ARPU_Gap,cat_target_ARPU
0,TEL-000001,SUB4640,2024-12-06,Yogyakarta,Jawa Barat,Data,Package_31,10,306.02,NaN,...,Retail,Cash,0,N,63,96010,805.83,Bagus,-92949.80,N
1,TEL-000002,SUB1687,2024-07-10,Surabaya,DIY,Data,Package_12,17,133.81,0.95,...,Dealer,Ewallet,57,N,86,76332,-17.38,Bagus Sekali,-76218.26,N
2,TEL-000003,SUB3131,2024-03-13,NaN,Jakarta,Data,Package_61,14,194.08,0.10,...,dealer,Transfer,81,N,96,154577,-92.57,Bagus Sekali,-152600.31,N
3,TEL-000004,SUB4293,2026-02-11,Bandung,Jakarta,Voice,Package_94,7,794.58,0.15,...,Online,Ewallet,108,N,54,91707,1152.86,Bagus,-86979.25,N
4,TEL-000005,SUB4930,2026-01-16,Surabaya,NaN,Data,Package_34,13,81.33,0.05,...,Online,Transfer,19,Y,27,182593,566.24,Buruk,-181004.89,N

In [48]:
df.groupby('Churn_Flag')['Activation_Date'].agg(
    ['count','mean','median','min','max']
)

,count,mean,median,min,max
Churn_Flag,,,,,
N,5064,2025-01-21 05:51:11.090047232,2025-01-21,2023-09-03,2026-06-19
Y,4936,2025-01-26 21:01:10.016207616,2025-01-21,2023-09-03,2026-06-19

In [49]:
pd.crosstab(
    df['Activation_Date'],
    df['Churn_Flag'],
    normalize='index'
) * 100

Churn_Flag               N          Y
Activation_Date
2023-09-03       53.846154  46.153846
2023-09-04       60.000000  40.000000
2023-09-05       66.666667  33.333333
2023-09-06       66.666667  33.333333
2023-09-07       36.363636  63.636364
...                    ...        ...
2026-06-15       60.000000  40.000000
2026-06-16       40.000000  60.000000
2026-06-17       57.142857  42.857143
2026-06-18       63.636364  36.363636
2026-06-19       80.000000  20.000000

[1021 rows x 2 columns]

In [ ]:
from sqlalchemy import create_engine

#DATABASE_URL = (#postgresql://postgres:Sct4otc_WeEmQL6pUo23@my-first-postgres-service-84fd3552.pg1dz3pskr6e7nnq6gt36faq4g.c0.ap-northeast-1.aws.pg.clickhouse.cloud:5432/postgres")

#engine = create_engine(DATABASE_URL,
    #connect_args={"options": "-c statement_timeout=36000000"}
#)

In [ ]:
#push_tables = {
   # 'telco': df
#}

#for table_name, df in push_tables.items():

   # print(f'Mengirim tabel {table_name} ke database...')

    #df.to_sql(
      #  table_name,engine,if_exists='replace',index=False
    #)